### ISSUE TITLE
td4 : la ligne de code suggérée pour montrer un toast ne montre pas un toast 

### ISSUE THREAD

**Issue by spawnie-no-oni** [tutorials-android/td#3]
Dans **Prendre une photo** > **Les permissions**

La ligne de code
`Toast.makeText(this, "We need access to your camera to take a picture :'(", Toast.LENGTH_LONG)`

devrait être

`Toast.makeText(this, "We need access to your camera to take a picture :'(", Toast.LENGTH_LONG).show()`

**Comment by LolWalid** [comment]
Corrigé !
